### ISSUE TITLE
Issue when doing pcs login - Error: Cannot find module 'azure-arm-containerservice'

### ISSUE THREAD

**Issue by falloutxAY** [Microsoft/MCW-IoT-and-the-Smart-City#12]
When doing `pcs login`

It returns with below error:

C:\Users\demouser\AppData\Roaming\npm>pcs login

> internal/modules/cjs/loader.js:582
>     throw err;
>     ^
> 
> Error: Cannot find module 'azure-arm-containerservice'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)
>     at Object.<anonymous> (C:\Users\demouser\AppData\Roaming\npm\node_modules\iot-solutions\publish\deploymentmanager.js:11:38)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
>     at Module.load (internal/modules/cjs/loader.js:598:32)
>     at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
>     at Function.Module._load (internal/modules/cjs/loader.js:529:3)

**Comment by akn9050** [comment]
PCS login is working now

**Comment by akn9050** [comment]
there is one more issue after login with PCS during Solution deployment. 
# Issue: Stuck while running pcs command too deploy solution
# Description 
After running PCS command, provided solution name, after that selected subscription and press enter but after that nothing is happening.
![snag_13113cfc](https://user-images.githubusercontent.com/27498287/48698835-1a50cb80-ec0e-11e8-840d-50bc7a28bb59.png)

**Comment by toddwhitehead** [comment]
Confirmed same issue, after selecting subscription never prompted for location

**Comment by akn9050** [comment]
yes

**Comment by joelhulen** [comment]
I believe this may be a problem with the provided VM. Could you please try the steps that lead to the PCS login from either a new VM (using Windows 10 or Server 2016 with the latest build of Visual Studio) or your own machine and see if you get past this? This will help verify the issue is with the specific VM image we are using.

**Comment by toddwhitehead** [comment]
The issue is an issue with the underlying pcs code (https://github.com/Azure/pcs-cli/issues/414)

**Comment by joelhulen** [comment]
Looks like the issue is now closed, yet it's not available until the next release: <https://github.com/Azure/pcs-cli/issues/414>

**Comment by akn9050** [comment]
This issue is no more. Facing issue in [Exercise 3 task 5](https://github.com/Microsoft/MCW-IoT-for-business/blob/master/Hands-on%20lab/HOL%20step-by-step%20-%20IoT%20for%20business.md#task-5-run-the-simulator-web-app-and-create-a-new-simulation) when running simulator web app. 
1. In first run it was showing error environment variable **PCS_IOTHUB_CONNSTRING** not available. This is not described to add for WebService project in lab guide.
1. After adding environment **PCS_IOTHUB_CONNSTRING**. Popup new error in 2nd run environment varible **PCS_STORAGEADAPTER_WEBSERVICE_URL** not available. I added this also.
1. In 3rd run getting another error. 
##Error
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Microsoft.Azure.IoTSolutions.DeviceSimulation.Services

1. And in task 1.5, when doing get method for  http://localhost:9003/v1/simulations/1. Then getting status 500 instead of 200.
